### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by FightMan01** [mkorkmaz/flightradar24#8]
```
Traceback (most recent call last):
  File "/home/Fightman01Bot/fightman01 debug/valuta.py", line 1811, in fl24
    fr = flightradar24.Api()
  File "/usr/local/lib/python3.8/dist-packages/flightradar24/core.py", line 28, in __init__
    response = api_request(self.balanceJsonUrl, self.proxies)
  File "/usr/local/lib/python3.8/dist-packages/flightradar24/helpers.py", line 17, in api_request
    return r.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.8/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by JeanExtreme002** [comment]
> ```
> Traceback (most recent call last):
>   File "/home/Fightman01Bot/fightman01 debug/valuta.py", line 1811, in fl24
>     fr = flightradar24.Api()
>   File "/usr/local/lib/python3.8/dist-packages/flightradar24/core.py", line 28, in __init__
>     response = api_request(self.balanceJsonUrl, self.proxies)
>   File "/usr/local/lib/python3.8/dist-packages/flightradar24/helpers.py", line 17, in api_request
>     return r.json()
>   File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
>     return complexjson.loads(self.text, **kwargs)
>   File "/usr/local/lib/python3.8/dist-packages/simplejson/__init__.py", line 525, in loads
>     return _default_decoder.decode(s)
>   File "/usr/local/lib/python3.8/dist-packages/simplejson/decoder.py", line 370, in decode
>     obj, end = self.raw_decode(s)
>   File "/usr/local/lib/python3.8/dist-packages/simplejson/decoder.py", line 400, in raw_decode
>     return self.scan_once(s, idx=_w(s, idx).end())
> simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> ```

Take a look at this [package](https://github.com/JeanExtreme002/FlightRadarAPI).

**Comment by mkorkmaz** [comment]
@FightMan01 Hi, sorry for the issue you have experienced. You need to update the library to use it without a problem.

Would you try again after updating the library:

```bash
pip3 install -U flightradar24
```
